---
- hosts: proxy
  name: Simple nginx example Vagrant Ansible Local
  become: yes

  tasks:

  - name: Update apt cache
    apt:
       update_cache: yes

  - name: Install nginx
    apt:
      name: nginx
      state: present

  - name: Copy Load-balancer config
    template:
      src: ./load-balancer.conf
      dest: /etc/nginx/conf.d/load-balancer.conf

  - name: Remove default config
    file:
      state: absent
      path: "/etc/nginx/sites-enabled/default"

  - name: Start NGiNX
    service:
      name: nginx
      state: started

