---
# tasks file for provision/roles/proxy

  - name: Copy Load-balancer config
    template:
      src: "{{ role_path }}/files/load-balancer.conf"
      dest: "/etc/nginx/conf.d/load-balancer.conf"
      remote_src: yes

  - name: Remove default config
    file:
      state: absent
      path: "/etc/nginx/sites-enabled/default"

  - name: Reload service NGiNX
    service:
      name: "{{ proxy.service }}"
      state: restarted

